/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package net.lingala.zip4j;

import net.lingala.zip4j.core.ZipFile;
import net.lingala.zip4j.model.UnzipParameters;
import org.junit.Test;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

public class AppTest {
	private static final String SOURCE_ZIP;
	private static UnzipParameters freshenParams = new UnzipParameters();
	private static UnzipParameters unFreshenParams = new UnzipParameters();

	static {
		try {

			freshenParams.setFreshen(true);
			SOURCE_ZIP = new File(AppTest.class.getResource("/source.zip").toURI()).getAbsolutePath();
		} catch (Exception e) {
			throw new RuntimeException("did not find source path");
		}
	}

	public static void unzip(String filePath, Path unzipdir, UnzipParameters zParameters) throws Exception {
		ZipFile zipfile = new ZipFile(filePath);
		zipfile.extractAll(unzipdir.toAbsolutePath().toString(), zParameters);
	}

	@Test
	public void test01UnZipFreshen() throws Exception {
		Path tempDir = Files.createTempDirectory("testUnZipFreshen");
		unzip(SOURCE_ZIP, tempDir, freshenParams);
		appendSomeThing(new File(tempDir.toFile(), "test.txt").toString());
		unzip(SOURCE_ZIP, tempDir, freshenParams);

	}

	private static void appendSomeThing(String filename) {
		try {
			FileWriter fw = new FileWriter(filename, true); //the true will append the new data
			fw.write("add a line\n");//appends the string to the file
			fw.close();
		} catch (IOException ioe) {
			System.err.println("IOException: " + ioe.getMessage());
		}

	}
}
